services:
  app:
    build: .
    container_name: beauty_app
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: npx ng serve --host 0.0.0.0 --poll 2000
    stdin_open: true
    tty: true

volumes:
  node_modules:
